app/forms/ContactForm.py
"""
.. module:: ContactForm
    :synopsis: A form for editing a :class:`~app.models.User`.

.. moduleauthor:: Dan Schlosser <dan@dan@schlosser.io>
"""

from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField
from wtforms.validators import Required, Email

EMAIL_ERROR = 'Please pass a working email address.'


class ContactForm(Form):
    """A form for editing a :class:`~app.models.User`.

    :ivar name: :class:`wtforms.fields.StringField` - The user's name
    :ivar email: :class:`wtforms.fields.StringField` - The user's email address
    """
    name = StringField('who are you?', [Required('Please type a name.')])
    email = StringField('what is your email?',
                        [Email(message=EMAIL_ERROR),
                         Required(message=EMAIL_ERROR)])
    message = TextAreaField('how can we help?',
                            [Required('Please type a message.')])

app/forms/__init__.py
from ContactForm import ContactForm

# Silence flake8 by referencing otherwise unused imports
__all__ = ['ContactForm']

app/__init__.py
"""
.. module:: __init__
    :synopsis: This is where all our global variables and instantiation
        happens. If there is simple app setup to do, it can be done here, but
        more complex work should be farmed off elsewhere, in order to keep
        this file readable.

.. moduleauthor:: Dan Schlosser <dan@dan@schlosser.io>
"""

import json
import logging

from flask import Flask
from flask.ext.assets import Environment, Bundle


app = None
adi = dict()
assets = None
gcal_client = None


def create_app(**config_overrides):
    """This is normal setup code for a Flask app, but we give the option
    to provide override configurations so that in testing, a different
    database can be used.
    """
    from app.routes.base import register_error_handlers

    # we want to modify the global app, not a local copy
    global app
    global adi
    global assets
    global gcal_client
    app = Flask(__name__)

    # Load config then apply overrides
    app.config.from_object('config.flask_config')
    app.config.update(config_overrides)

    # Initialize assets
    assets = Environment(app)
    register_scss()

    # Attach Blueprints (routing) to the app
    register_blueprints(app)

    # Attache error handling functions to the app
    register_error_handlers(app)

    # Register the logger.
    register_logger(app)

    return app


def register_logger(app):
    """Create an error logger and attach it to ``app``."""

    max_bytes = int(app.config["LOG_FILE_MAX_SIZE"]) * 1024 * 1024   # MB to B
    # Use "# noqa" to silence flake8 warnings for creating a variable that is
    # uppercase.  (Here, we make a class, so uppercase is correct.)
    Handler = logging.handlers.RotatingFileHandler  # noqa
    f_str = ('%(levelname)s @ %(asctime)s @ %(filename)s '
             '%(funcName)s %(lineno)d: %(message)s')

    access_handler = Handler(app.config["WERKZEUG_LOG_NAME"],
                             maxBytes=max_bytes)
    access_handler.setLevel(logging.INFO)
    logging.getLogger("werkzeug").addHandler(access_handler)

    app_handler = Handler(app.config["APP_LOG_NAME"], maxBytes=max_bytes)
    formatter = logging.Formatter(f_str)
    app_handler.setLevel(logging.INFO)
    app_handler.setFormatter(formatter)
    app.logger.addHandler(app_handler)


def register_blueprints(app):
    """Registers all the Blueprints (modules) in a function, to avoid
    circular dependancies.

    Be careful rearranging the order of the app.register_blueprint()
    calls, as it can also result in circular dependancies.
    """
    from app.routes import client
    app.register_blueprint(client)


def register_scss():
    """Registers the Flask-Assets rules for scss compilation.  This reads from
    ``config/scss.json`` to make these rules.
    """
    assets.url = app.static_url_path
    with open(app.config['SCSS_CONFIG_FILE']) as f:
        bundle_set = json.loads(f.read())
        output_folder = bundle_set['output_folder']
        depends = bundle_set['depends']
        for bundle_name, instructions in bundle_set['rules'].iteritems():
            bundle = Bundle(*instructions['inputs'],
                            output=output_folder + instructions['output'],
                            depends=depends,
                            filters='scss')
            assets.register(bundle_name, bundle)


def run():
    """Runs the app."""
    app.run(host=app.config.get('HOST'), port=app.config.get('PORT'))

app/routes/__init__.py
from app.routes.client import client

# Silence flake8 by referencing otherwise unused imports
__all__ = ['client']

app/routes/base.py
"""
.. module:: base
    :synopsis: All routes on the ``base`` Blueprint, as well as error handlers,
        before and after request handlers, and context processors.

.. moduleauthor:: Dan Schlosser <dan@dan@schlosser.io>
"""

from flask import render_template, request, url_for
import sys

SUPER_USER_GPLUS_ID = 'super'
ERROR_FLASH = 'error'
MESSAGE_FLASH = 'message'


def register_error_handlers(app):

    @app.errorhandler(Exception)
    def exception_handler(error):
        """Handle uncaught exceptions."""
        app.logger.error("Uncaught Exception", exc_info=sys.exc_info())
        app.handle_exception(error)  # default error handler

    @app.errorhandler(400)
    def bad_request(error):
        """Handle 400 errors."""
        return render_template('error/400.html'), 400

    @app.errorhandler(401)
    def not_authorized(error):
        """Handle 401 errors."""
        return render_template('error/401.html'), 401

    @app.errorhandler(403)
    def forbidden(error):
        """Handle 403 errors."""
        return render_template('error/403.html'), 403

    @app.errorhandler(404)
    def not_found(error):
        """Handle 404 errors."""
        return render_template('error/404.html'), 404

    @app.errorhandler(405)
    def method_not_allowed(error):
        """Handle 405 errors."""
        return render_template('error/405.html', method=request.method), 405

    @app.errorhandler(500)
    def internal_server_error(error):
        """Handle 500 errors."""
        return render_template('error/500.html'), 500

    @app.context_processor
    def inject_helpers():
        """Injects a dictionary of helper variables and functions into Jinja
        templates.
        """
        helpers = {
            'static': lambda filename: url_for('static', filename=filename)
        }
        return helpers

    @app.after_request
    def add_header(response):
        """
        Add headers to both force latest IE rendering engine or Chrome Frame,
        and also to cache the rendered page for 10 minutes.
        """
        response.headers['X-UA-Compatible'] = 'IE=Edge,chrome=1'
        response.headers['Cache-Control'] = 'public, max-age=0'
        return response

app/routes/client.py
"""
.. module:: client
    :synopsis: All routes on the ``client`` Blueprint.

.. moduleauthor:: Dan Schlosser <dan@dan@schlosser.io>
"""

from flask import Blueprint, render_template
from app.lib.json_response import json_success, json_error_message
from app.forms import ContactForm
client = Blueprint('client', __name__)


@client.route('/', methods=['GET'])
def contact():
    """View the homepage.

    **Route:** ``/``

    **Methods:** ``GET``
    """
    form = ContactForm(prefix="minimill-")
    return render_template('contact.html', form=form)


@client.route('/', methods=['POST'])
def email_us():
    """Email the team.

    **Route:** ``/``

    **Methods:** ``GET``
    """
    form = ContactForm()
    if form.validate_on_submit():
        return json_success({})
    error_message = form.errors.items()[0][1][0]
    return json_error_message(error_message, error_data=form.errors)


@client.route('/team', methods=['GET'])
def team():
    """View the team.

    **Route:** ``/team``

    **Methods:** ``GET``
    """
    return render_template('team.html')

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {%- block meta -%}
    <meta charset="utf-8" />
    <title>{%- block title-%}{{ config.META_TITLE }}{%- endblock -%}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="{{ config.META_DESCRIPTION }}" />
    <meta name="robots" content="NOODP, index, follow" />
    <meta itemprop="name" content="{{ config.META_TITLE }}">
    <meta itemprop="description" content="{{ config.META_DESCRIPTION }}">
    <meta itemprop="image" content="{{ url_for('static', filename=config.META_IMAGE) }}">
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="{{ config.META_TWITTER_HANDLE }}">
    <meta name="twitter:title" content="{{ config.META_TITLE }}">
    <meta name="twitter:description" content="{{ config.META_DESCRIPTION }}">
    <meta name="twitter:creator" content="{{ config.META_TWITTER_HANDLE }}">
    <meta name="twitter:image:src" content="{{ url_for('static', filename=config.META_IMAGE) }}">
    <meta name="twitter:domain" content="{{ config.META_DOMAIN }}">
    <!-- Open Graph data (Facebook) -->
    <meta property="og:title" content="{{ config.META_TITLE }}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ config.META_URL + request.path }}" />
    <meta property="og:image" content="{{ url_for('static', filename=config.META_IMAGE) }}" />
    <meta property="og:description" content="{{ config.META_DESCRIPTION }}" />
    <!-- Apple Icons -->
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="{{ static('img/favicon/favicon-57x57.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ static('img/favicon/favicon-114x114.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ static('img/favicon/favicon-72x72.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ static('img/favicon/favicon-144x144.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="{{ static('img/favicon/favicon-60x60.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="{{ static('img/favicon/favicon-120x120.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="{{ static('img/favicon/favicon-76x76.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="{{ static('img/favicon/favicon-152x152.png') }}" />
    <!-- Standard Icons -->
    <link rel="icon" type="image/png" href="{{ static('img/favicon/favicon-196x196.png') }}" sizes="196x196" />
    <link rel="icon" type="image/png" href="{{ static('img/favicon/favicon-96x96.png') }}" sizes="96x96" />
    <link rel="icon" type="image/png" href="{{ static('img/favicon/favicon-32x32.png') }}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{{ static('img/favicon/favicon-16x16.png') }}" sizes="16x16" />
    <link rel="icon" type="image/png" href="{{ static('img/favicon/favicon-128.png') }}" sizes="128x128" />
    <!-- Microsoft Metadata -->
    <meta name="application-name" content="{{ config.META_TITLE }}"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="{{ static('img/favicon/favicon-144x144.png') }}" />
    <meta name="msapplication-square70x70logo" content="{{ static('img/favicon/favicon-70x70.png') }}" />
    <meta name="msapplication-square150x150logo" content="{{ static('img/favicon/favicon-150x150.png') }}" />
    <meta name="msapplication-wide310x150logo" content="{{ static('img/favicon/favicon-310x150.png') }}" />
    <meta name="msapplication-square310x310logo" content="{{ static('img/favicon/favicon-310x310.png') }}" />
    {%- endblock meta-%}
    {%- block css-%}
    <link rel="stylesheet" type="text/css" href="{{ static('css/lib/reset.min.css') }}">
    {%- endblock css-%}
    {%- block analytics -%}
    <!-- Google Analytics go here -->
    {%- endblock -%}
</head>
<body>
    {%- block body -%}{%- endblock -%}
    {%- block js -%}
    <!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->
    {%- endblock -%}
</body>
</html>

app/templates/contact.html
{%- extends "template.html" -%}
{% import "macros.html" as macros %}
{%- block title -%}{{ super() }}{%- endblock -%}

{%- block js -%}
{{ super() }}
<script type="text/javascript" src="{{ static('js/index.js') }}"></script>
{%- endblock -%}

{%- block content -%}
<h1 class="headline">We are Minimill, a new design agency.<br>Let's work together.</h1>
<form id="contact-form" action="{{ url_for('client.contact') }}" method="POST" autocomplete="off">
    {{macros.render_field(form.name, class="field", required="true", spellcheck="false", autocomplete="off")}}
    {{macros.render_field(form.email, class="field", required="true", spellcheck="false", autocomplete="off")}}
    {{macros.render_field(form.message, class="field", required="true", spellcheck="false", autocomplete="off")}}
    <div class="hidden-fields">
        {{macros.render_field(form.csrf_token)}}
        <input type="submit" id="submit" value="submit" />
    </div>
</form>
<div id="submit-button" class="submit-button">
    <div class="content">
        <span class="submit-button-label">Send</span>
        <span id="error-message">Yikes, something went awry.</span>
    </div>
</div>
<div id="success-sheet">
    <div class="content">
        <p class="to"><span id="to-name">Gerald</span>,</p>
        <p>Thanks for reaching out.</p>
        <p>We’ll get back to you really soon.</p>
        <p class="from">- Jeff and Dan</p>
    </div>
</div>
{%- endblock -%}

app/templates/macros.html
{%- macro render_field(field, label=True, hidden=False) -%}
{%- set class = kwargs.get('class', '') + ' form-control' -%}
{%- if field.errors -%}{%- set class = class + ' invalid' -%}{%- endif -%}
{%- if hidden -%}{%- set class = class + ' hidden' -%}{%- endif -%}
<div class="{{class}}">
	{{ field(class=class, placeholder=field.label.text, **kwargs) | safe }}
	{%- if field.errors -%}
	<ul class="errors">
		{%- for error in field.errors -%}
	  	<li>{{ error }}</li>
		{%- endfor -%}
	</ul>
	{%- endif -%}
</div>
{%- endmacro -%}

app/templates/minimill-logo.svg.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 248 88">
<g>
    <rect x="216" width="8" height="88"/>
    <rect x="240" width="8" height="88"/>
    <polygon points="144,0 144,88 152,88 152,8 168,8 168,88 176,88 176,8 192,8 192,24 200,24 200,0"/>
    <rect x="192" y="40" width="8" height="8"/>
    <rect x="192" y="64" width="8" height="24"/>
    <polygon points="0,0 0,88 8,88 8,8 24,8 24,88 32,88 32,8 48,8 48,24 56,24 56,0"/>
    <rect x="48" y="40" width="8" height="8"/>
    <rect x="48" y="64" width="8" height="24"/>
    <rect x="120" width="8" height="8"/>
    <rect x="120" y="24" width="8" height="64"/>
    <polygon points="72,0 72,88 80,88 80,8 96,8 96,88 104,88 104,0"/>
</g>
</svg>

app/templates/team.html
{%- extends "template.html" -%}
{%- block title -%}{{ super() }} - Team{%- endblock -%}

{%- block content -%}
{%- endblock -%}

app/templates/template.html
{% extends "base.html" %}

{%- block css -%}
{{ super() }}
{%- assets "scss_all" -%}
<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
{%- endassets -%}
{%- endblock -%}

{% block body %}
<section id="main">
    <div class="content">
        {% block content %}
        {% endblock%}
    </div>
    <footer>
        <div class="content">
            <a href="/">
                <div class="logo">
                    {% include "minimill-logo.svg.html" %}
                </div>
            </a>
            <p>design and dev and brand and people</p>
        </div>
    </footer>
</section>
{% endblock %}